--- #YAML:1.0
name:                TiVo-Calypso
version:             1.3.5
abstract:            A Perl interface to the TiVo Calypso protocol
license:             perl
distribution_type:   module
requires:
    Storable:               0
    IO::File:               0
    MP3::Info:              0
    Digest::MD5:            0
    Encode:                 0
    LWP::Simple:            0
author:
    - Scott Schneider <sschneid@gmail.com>

