abstract: a Perl interface to the TiVo Calypso protocol
author: 'Scott Schneider  C<< <sschneid@gmail.com> >>'
#build_requires:
#  Test::Distribution: 1.23
#  Test::More: 0.62
distribution_type: module
#generated_by: Module::Install version 0.61
license: gpl
name: TiVo-Calypso
no_index:
  directory:
    - inc
    - t
#requires:
#  Class::Base: 0.03
#  Config::Tiny: 2.05
#  Crypt::SmbHash: 0.12
#  Digest::MD5: 2.36
#  Digest::SHA1: 2.11
#  File::Path: 0
#  List::MoreUtils: 0.19
#  MIME::Base64: 3.07
#  Net::LDAP: 0.33
#  Readonly: 1.03
#  Regexp::DefaultFlags: 0.01
#  UNIVERSAL::require: 0.10
#  Unicode::MapUTF8: 1.11
#  perl: 5.6.0
version: 1.3.3
